services:
  invoices-pg:
    image: bitnami/postgresql:latest
    ports:
      - "5483:5432" # porta-da-maquina:porta-do-container
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
